DEFAULT_TAG_LABELS = [
    "ATM",
    "Bars & Restaurants",
    "Education",
    "Family & Friends",
    "Food & Groceries",
    "Healthcare & Drug Stores",
    "Household & Utilities",
    "Income",
    "Insurances & Finances",
    "Leisure & Entertainment",
    "Media & Electronics",
    "Miscellaneous",
    "Salary",
    "Savings & Investments",
    "Shopping",
    "Subscriptions & Donations",
    "Tax & Fines",
    "Transport & Car",
    "Travel & Holidays",
]
